### ISSUE TITLE
fails to generate Python client with openapi generator

### ISSUE THREAD

**Issue by ekoby** [openziti/edge-api#38]
run generator:
`$ openapi-generator-cli generate -g python -o ./python -i client.yml `

Error:

```
Exception in thread "main" java.lang.RuntimeException: Your spec version of 2.0 is too low. python only works with specs with version >= 3.X.X. Please use a tool like Swagger Editor or Swagger Converter to convert your spec to v3
	at org.openapitools.codegen.languages.PythonClientCodegen.preprocessOpenAPI(PythonClientCodegen.java:2773)
	at org.openapitools.codegen.DefaultGenerator.configureGeneratorProperties(DefaultGenerator.java:272)
	at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:935)
	at org.openapitools.codegen.cmd.Generate.execute(Generate.java:487)
	at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
```

**Comment by sabedevops** [comment]
@ekoby You need to pull the latest version of that image or instead use the `python-prior` generator for V2 support. In later versions of their project, `python-prior` is removed and V2 function is merged with the `python` generator. 

Relevant discussion on breakage in the newest version and why I recommend `python-prior` approach: https://openziti.discourse.group/t/management-api-authentication/1480/31

**Comment by ekoby** [comment]
Python was just a side quest as I was looking into generating other clients (see #39). 
In my opinion we should support latest tools out of the box, or at least document needed workarounds in the README
